---

- name: Get ReplicaSet member status
  set_fact:
    mongo_offer_provider: "{{ vitam_offers[hostvars[inventory_hostname]['mongo_cluster_name']]['provider'] }}"

- name: Check if node is master or not
  command: "mongo --host {{ ip_service }} --port {{ mongo_port }} --quiet --eval 'rs.isMaster().ismaster'"
  register: isMaster

- name: Get ReplicaSet member status (mongod)
  set_fact:
    mongod_is_master: "{{ isMaster.stdout_lines|first|lower }}"
  when: mongo_type == "mongod"

- name: Get ReplicaSet member status (mongoc)
  set_fact:
    mongoc_is_master: "{{ isMaster.stdout_lines|first|lower }}"
  when: mongo_type == "mongoc"
