- name: install ihm-recette-front
  package:
    name: vitam-ihm-recette-front
    state: latest
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  tags:
    - update_package_vitam
