{% if inventory_hostname in groups['hosts_elasticsearch_data'] %}
- module: elasticsearch
  period: {{ metricbeat.elasticsearch.period }}s
  hosts: ["{{ ip_service }}:{{ elasticsearch.data.port_http }}"]
  metricsets: ["node", "node_stats"]
{% endif %}