{% if inventory_hostname in groups['hosts_mongoc_data'] %}
- module: mongodb
  hosts: ["{{ ip_service }}:{{ mongodb.mongoc_port }}"]
  metricsets: ["collstats","dbstats", "status"]
  username: {{ mongodb['mongo-data']['localadmin']['user'] }}
  password: {{ mongodb['mongo-data']['localadmin']['password'] }}
  period: {{ metricbeat.mongodb.period }}s
{% endif %}

{% if inventory_hostname in groups['hosts_mongod_data'] %}
- module: mongodb
  hosts: ["{{ ip_service }}:{{ mongodb.mongod_port }}"]
  metricsets: ["dbstats", "status", "metrics", "replstatus"]
  username: {{ mongodb['mongo-data']['localadmin']['user'] }}
  password: {{ mongodb['mongo-data']['localadmin']['password'] }}
  period: {{ metricbeat.mongodb.period }}s
{% endif %}

{% if inventory_hostname in groups['hosts_mongos_data'] %}
- module: mongodb
  hosts: ["{{ ip_service }}:{{ mongodb.mongos_port }}"]
  metricsets: ["dbstats", "status"]
  username: {{ mongodb['mongo-data']['admin']['user'] }}
  password: {{ mongodb['mongo-data']['admin']['password'] }}
  period: {{ metricbeat.mongodb.period }}s
{% endif %}

{% if inventory_hostname in groups['hosts_mongoc_offer'] and inventory_hostname not in groups['hosts_mongoc_data'] %}
- module: mongodb
  hosts: ["{{ ip_service }}:{{ mongodb.mongoc_port }}"]
  metricsets: ["collstats","dbstats", "status"]
  username: {{ mongodb[mongo_cluster_name]['localadmin']['user'] }}
  password: {{ mongodb[mongo_cluster_name]['localadmin']['password'] }}
  period: {{ metricbeat.mongodb.period }}s
{% endif %}

{% if inventory_hostname in groups['hosts_mongod_offer'] and inventory_hostname not in groups['hosts_mongod_data'] %}
- module: mongodb
  hosts: ["{{ ip_service }}:{{ mongodb.mongod_port }}"]
  metricsets: ["dbstats", "status"]
  username: {{ mongodb[mongo_cluster_name]['localadmin']['user'] }}
  password: {{ mongodb[mongo_cluster_name]['localadmin']['password'] }}
  period: {{ metricbeat.mongodb.period }}s
{% endif %}

{% if inventory_hostname in groups['hosts_mongos_offer'] and inventory_hostname not in groups['hosts_mongos_data'] %}
- module: mongodb
  hosts: ["{{ ip_service }}:{{ mongodb.mongos_port }}"]
  metricsets: ["dbstats", "status"]
  username: {{ mongodb[mongo_cluster_name]['admin']['user'] }}
  password: {{ mongodb[mongo_cluster_name]['admin']['password'] }}
  period: {{ metricbeat.mongodb.period }}s
{% endif %}
