---

- name: Update yum cache
  yum:
    name: "yum"
    state: present
    update_cache: yes
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  tags:
    - enable_vitam_repo
    - update_package_vitam
  when: ansible_os_family == "RedHat"


- name: run apt-update
  apt:
    update_cache: yes
  tags:
    - enable_vitam_repo
    - update_package_vitam
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  when: ansible_os_family == "Debian"

