---
# tasks file for vitam_autotest

- name: "Check if {{ vitam_component }} is listening on business port {{ check_port_service }}"
  wait_for:
    host: "{{ hote_service }}"
    port: "{{ check_port_service }}"
    state: started
  when: ( primary_site | lower == "true" ) or
        ( vitam_component in vitam_secondary_site_components )

- name: "Check autotest for {{ vitam_component }} component on admin port {{ check_port }}"
  uri:
    url: '{{ protocol }}://{{ hote }}:{{ check_port }}/admin/v1/autotest'
    method: GET
    status_code: 200
    validate_certs: no
    return_content: yes
    timeout: "{{ vitam_defaults.services.api_call_timeout }}"
  register: response
  when: ( primary_site | lower == "true" ) or
        ( vitam_component in vitam_secondary_site_components )

- block:
  - name: debug for {{ vitam_component }} component
    debug: var=(response.json.message)
    when: response is succeeded 

  - name: fail if not OK
    fail:
      msg: "{{ response.json.message }}"
    when: response is failed

  - name: fail if not correct response
    fail:
      msg: "{{ response.json.message }}"
    when: response.json.message != 'All services are available'
  
  when: response is defined