---

- name: Compute the offers list
  set_fact: offer_item="{{ item }}"
  when:
    - "offer_conf == hostvars[item]['offer_conf']"
  with_items:
    - "{{ groups['hosts_storage_offer_default'] }}"
  register: offer_result
  
- name: make a list from the result
  set_fact:
    offer_list: "{{ offer_result.results | remove_skipped_servers | map(attribute='ansible_facts.offer_item') | list }}"
  when: "inventory_hostname not in single_vm_hostnames"
  
  
- name: make a list from the result (localhost deploy)
  set_fact:
    offer_list: [ 'localhost' ]
  when: "inventory_hostname in single_vm_hostnames"

- name: Check timer is loaded 
  shell: "systemctl status vitam-offer-log-compaction.timer"
  register: timer_systemd
  failed_when: timer_systemd.rc|int > 0
  when: inventory_hostname == offer_list|last
  