---
# Exemple : localhost offer_conf=offer-fs-1

- name: ensure python-pip is installed
  package:
    name: python-pip
    state: present

- pip:
    name: pip
  environment:
      http_proxy: "{{ http_proxy_environnement }}"
      https_proxy: "{{ http_proxy_environnement }}"
  when: http_proxy_environnement is defined and http_proxy_environnement != ""

- pip:
    name: pip
  when: http_proxy_environnement is not defined or http_proxy_environnement == ""

- set_fact:
    containerList: ["accessionregisterdetail", "accessionregistersymbolic", "archivaltransferreply", "backup_operation", "check_logbookreports", "dip", "logbook", "manifest", "object", "objectGroup", "report", "storageaccesslog", "storagelog", "storagetraceability", "tmp", "unit", "unitgraph"]
    containerRegExp: (?:accessionregisterdetail|accessionregistersymbolic|archivaltransferreply|backup_operation|check_logbookreports|dip|logbook|manifest|object|objectGroup|report|storageaccesslog|storagelog|storagetraceability|tmp|unit|unitgraph)

# nettoyer les offres en filesystem ou filesystem-hash
- import_tasks: purge_fs.yml
  when: vitam_offers[offer_conf]["provider"] in ["filesystem","filesystem-hash"]

# nettoyer les offres s3
- import_tasks: purge_s3.yml
  when: (vitam_offers[offer_conf]["provider"] == "amazon-s3-v1")

# nettoyer les offres en openstack-swift ou openstack-swift-v3
- import_tasks: purge_swift.yml
  when: vitam_offers[offer_conf]["provider"] in ["openstack-swift","openstack-swift-v3"]
