---

- name: remove data in offer for filesystem or filesystem-hash
  file:
    path: "{{ vitam_defaults.folder.root_path }}/data/{{ vitam_struct.vitam_component }}/container/{{ vitam_prefix_offer|default(vitam_site_name) }}_{{ item[0] }}_{{ item[1] }}"
    state: absent
  with_nested:
    - "{{ vitam_tenant_ids }}"
    - "{{ containerList }}"

- name: create folder in offer for filesystem or filesystem-hash
  file:
    path: "{{ vitam_defaults.folder.root_path }}/data/{{ vitam_struct.vitam_component }}/container/{{ vitam_prefix_offer|default(vitam_site_name) }}_{{ item[0] }}_{{ item[1] }}"
    state: directory
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
  with_nested:
    - "{{ vitam_tenant_ids }}"
    - "{{ containerList }}"
