---

- name: Compute the mongos server list
  set_fact: mongos_item="{{ item }}"
  when:
    - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
  with_items:
    - "{{ groups[group_name] }}"
  register: mongos_result

- name: make a list from the result
  set_fact:
    mongos_list: "{{ mongos_result.results | remove_skipped_servers | map(attribute='ansible_facts.mongos_item') | list }}"
  when: "inventory_hostname not in single_vm_hostnames"

- block:

    - name: Install docker
      include_role:
        name: docker

    - name: Deploy mongo-express container
      docker_container:
        name: "mongo-express"
        image: "{{ mongo_express_image }}:{{ mongo_express_version }}"
        state: started
        restart_policy: always
        ports:
          - "{{ mongo_express_external_port }}:{{ mongo_express_port }}"
        env:
          ME_CONFIG_MONGODB_SERVER: "{{ ip_service }}"
          ME_CONFIG_MONGODB_PORT: "{{ mongodb.mongos_port }}"
          ME_CONFIG_SITE_BASEURL: "/{{ mongo_express.baseuri }}-{{ mongo_cluster_name }}/"
          ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
          ME_CONFIG_MONGODB_ADMINUSERNAME: "{{ mongodb[mongo_cluster_name]['admin']['user'] }}"
          ME_CONFIG_MONGODB_ADMINPASSWORD: "{{ mongodb[mongo_cluster_name]['admin']['password'] }}"

  when: mongos_list |first == inventory_hostname
