---

- name: Check timer is loaded on secundary site for ALL
  shell: "systemctl status {{ item[0] }}"
  register: timer_systemd
  failed_when: timer_systemd.rc|int > 0
  when: (inventory_hostname in groups[item[1]] ) and (item[3]|length > 0) and (item[3]=="in")
  loop :  "{{ vitam_timers_list }}"

- name: Check timer is enabled on secundary site for ALL
  shell: "systemctl status {{ item[0] }}"
  register: timer_systemd
  failed_when: timer_systemd.stdout|regex_search('inactive')
  when: (inventory_hostname in groups[item[1]] ) and (item[2]|length > 0) and (item[3]=="in")
  loop :  "{{ vitam_timers_list }}"

- name: Check timer is loaded on secundary site for LAST
  shell: "systemctl status {{ item[0] }}"
  register: timer_systemd
  failed_when: timer_systemd.rc|int > 0
  when: (inventory_hostname == groups[item[1]]|last ) and (item[3]|length > 0) and (item[3]=="last")
  loop :  "{{ vitam_timers_list }}"

- name: Check timer is enabled on secundary site for LAST
  shell: "systemctl status {{ item[0] }}"
  register: timer_systemd
  failed_when: timer_systemd.stdout|regex_search('inactive')
  when: (inventory_hostname == groups[item[1]]|last ) and (item[3]|length > 0) and (item[3]=="last")
  loop :  "{{ vitam_timers_list }}"