---

  - name: Get PID
    shell: "ps -ef | grep {{ vitam_struct.vitam_component }} | grep -v ansible | grep -v grep | awk '{print $2}'"
    register: pid

  - name: Take thread dump
    shell: "kill -3 {{ pid.stdout }}"
