---

- name: Get installed packages list
  package_facts:
    manager: auto
  tags: griffins

- name: Remove useless griffins
  package:
    name: "{{ item }}"
    state: absent
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  when:
    - item is match("vitam-\S*-griffin")
    - item not in vitam_griffins
  loop: "{{ ansible_facts.packages |list }}"
  tags: griffins

# vitam_griffins var is a list
- name: Install griffins packages
  package:
    name: "{{ vitam_griffins }}"
    state: latest
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  tags: griffins

- name: Install selinux packages 
  package:
    name: "{{ item }}-selinux"
    state: latest
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  tags: griffins
  when:
    - selinux_state | lower in ["enforcing", "permissive"]
    - selinux_policy | lower == "targeted" # We don"t handle mls mode for now
  loop: "{{ vitam_griffins }}"