- name: Copy the database scripts files
  template:
    src: "update-offer.js.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/app/mongos/update-offer.js"
    owner: "{{ vitam_defaults.users.vitamdb }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"

- block:

  - name: Compute the mongos offer server list
    set_fact: mongos_item="{{ item }}"
    when:
      - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
    with_items:
      - "{{ groups['hosts_mongos_offer'] }}"
    register: mongos_result

  - name: make a list from the result
    set_fact:
      mongos_list: "{{ mongos_result.results | remove_skipped_servers | map(attribute='ansible_facts.mongos_item') | list }}"
  
  - name: for debug
    debug:
      msg: "{{ mongos_list }}"

  when: "inventory_hostname not in single_vm_hostnames"

- name: make a list from the result (localhost deploy)
  set_fact:
    mongos_list: [ 'localhost' ]
  when: "inventory_hostname in single_vm_hostnames"

- name: launch script to purge mongo_offer
  command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin -u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet {{ vitam_defaults.folder.root_path }}/app/mongos/update-offer.js"
  when: "inventory_hostname == mongos_list|last"
# When last of this group

- name: Delete old file
  file:
    path: "{{ vitam_defaults.folder.root_path }}/app/mongos/update-offer.js"
    state: absent
