---

- hosts: hosts_storage_offer_default
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.storageofferdefault }}"

- hosts: hosts_storage_engine
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.storageengine }}"

- hosts: hosts_metadata
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.metadata }}"

- hosts: hosts_logbook
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.logbook }}"

- hosts: hosts_workspace
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.workspace }}"

- hosts: hosts_functional_administration
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.functional_administration }}"

- hosts: hosts_security_internal
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.security_internal }}"

- hosts: hosts_processing
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.processing }}"

- hosts: hosts_batch_report
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.batchreport }}"

- hosts: hosts_worker
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.worker }}"

- hosts: hosts_access_internal
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.accessinternal }}"

- hosts: hosts_access_external
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.accessexternal }}"

- hosts: hosts_ingest_internal
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.ingestinternal }}"

- hosts: hosts_ingest_external
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.ingestexternal }}"

- hosts: hosts_ihm_demo
  any_errors_fatal: true
  roles:
    - thread_dump
  vars:
    vitam_struct: "{{ vitam.ihm_demo }}"
