---

- name: remove data in workspace
  file:
    path: "{{ vitam_defaults.folder.root_path }}/data/{{ vitam_struct.vitam_component }}/"
    state: absent

- name: create folder in workspace
  file:
    path: "{{ vitam_defaults.folder.root_path }}/data/{{ vitam_struct.vitam_component }}/"
    state: directory
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.folder_permission }}"
